### ISSUE TITLE
hotkey cannot search selected text

### ISSUE THREAD

**Issue by zzzchuu** [sunwxg/gnome-shell-extension-dict#10]
After today‘s update,this extension's hotkey "ctrl+alt+o" only show my last search result and can't search my selection words.And clicking the icon at top bar can't search my selected words either.However if I click the icon appeared around the selected text,it turned out to be correct.

I tried to install an  old version,but the bug still appeared.

**Comment by zzzchuu** [comment]
Sry the v21 version is Ok on my system.But the latest version might has this bug indeed.
I'm also curious about what's updated recently since the new version seems nothing new but just having a bug to me.

~~才发现作者是中国人，我渣英文要被吐槽了。。大佬能给个QQ不~~

**Comment by sunwxg** [comment]
Create a new commit, you can try the latest version from github.

**Comment by zzzchuu** [comment]
> Create a new commit, you can try the latest version from github.

Thank you! it's fixed.
But threre's a new little problem..that there is a popup windows when I use `ctrl+alt+o`.
![2020-02-06 16-05-55 的屏幕截图](https://user-images.githubusercontent.com/40953911/73917642-c7d6fa00-48fa-11ea-8375-51866ad5bd81.png)

**Comment by sunwxg** [comment]
You need to install this extension https://extensions.gnome.org/extension/2182/noannoyance/

**Comment by zzzchuu** [comment]
Thanks,but it stopped itself ( ﾟ∀。)
Maybe i'll try that later.
