### ISSUE TITLE
Doesn't work in gnome 3.38

### ISSUE THREAD

**Issue by wuqso** [sunwxg/gnome-shell-extension-dict#12]
Is there a new version that works in gnome 3.38?

**Comment by sunwxg** [comment]
I'm preparing the GNOME 3.38 environment, wait a few days.
Thank you.

**Comment by wuqso** [comment]
That's really a good extension. Thank you for your work.


-----原始邮件-----
发件人:"Xiaoguang Wang" <notifications@github.com>
发送时间:2020-10-13 08:22:05 (星期二)
收件人: sunwxg/gnome-shell-extension-dict <gnome-shell-extension-dict@noreply.github.com>
抄送: wuqso <jhwu@bnu.edu.cn>, Author <author@noreply.github.com>
主题: Re: [sunwxg/gnome-shell-extension-dict] Doesn't work in gnome 3.38 (#12)



I'm preparing the GNOME 3.38 environment, wait a few days.
Thank you.
