### ISSUE TITLE
Do not move a pinned Dict window

### ISSUE THREAD

**Issue by Chinory** [sunwxg/gnome-shell-extension-dict#14]
When pinned Dict window lost focus, it moved to center of screen, which I think it should not

**Comment by sunwxg** [comment]
That's expected behavior.

**Comment by Chinory** [comment]
I think this should not be expected

![ADHD](https://user-images.githubusercontent.com/32269068/103600326-15f8e100-4f42-11eb-8bcd-bc93a04fcbe7.gif)

**Comment by sunwxg** [comment]
Yes, that's wrong.
