### ISSUE TITLE
the popup shows nothing

### ISSUE THREAD

**Issue by antonio24073** [sunwxg/gnome-shell-extension-dict#22]
Hi,
The popup looks like this:
![image](https://user-images.githubusercontent.com/40250610/104407090-9bcaec80-553f-11eb-96f7-d1fcbca36b38.png)
I tried debug with 
`journalctl /usr/bin/gnome-session -f -o cat 
`
but nothing happened.

**Comment by sunwxg** [comment]
Open a terminal, then run
```
killall dict.js
~/.local/share/gnome-shell/extensions/dict@sun.wxg@gmail.com/dict.js
```
then do the test.

**Comment by antonio24073** [comment]
When I run killall dict.js and press ctrl+alt+o it goes back to work.
Thank you.

**Comment by antonio24073** [comment]
Hi again,
The problem persists. I run killall dict.js and it works temporally.
