### ISSUE TITLE
Cannot scroll on the selection menu `Select target language`

### ISSUE THREAD

**Issue by re-hub** [sunwxg/gnome-shell-extension-dict#23]
Steps to produce:
1) open extensions application
2) click on "Screen word translate"
3) click on the selection menu of "Select target language"

what happens:
only part of the list appears, user cannot scroll to see the rest of options. In addition, if you move the settings window down,  selection menu goes down as well and fewer options are visible.

window protcol: wayland 
gnome-shell version:40.0
Screen word translate: 34

If you need more info let me know

**Comment by sunwxg** [comment]
Yes, it's a gtk4 bug. If you place the mouse point on the drop down button, don't click it, scroll mouse, you can see the language is changed.
I have fixed it, but not send to extensions.gnome.org. You can try the github latest version.

**Comment by re-hub** [comment]
Ok, thanks for great ork
