### ISSUE TITLE
There is no popup window in Fedora 37 Beta

### ISSUE THREAD

**Issue by wuqso** [sunwxg/gnome-shell-extension-dict#28]
This is really an excellent extention and I installed and used it for a long time. Recently, I upgraded my system from Fedora 36 into Fedora 37 Beta and installed the latest version of this extention. Then I found that there is no popup window for displaying the translations. What's the problem?

**Comment by sunwxg** [comment]
I create a new submit, try the new version.

**Comment by wuqso** [comment]
The new version works. Thank you very much!
