### ISSUE TITLE
Feature Request - An options menu with a list of explicit applications to allow or ignore use of the extension?

### ISSUE THREAD

**Issue by MostHated** [sunwxg/gnome-shell-extension-dict#3]
Hey there,
    I really like the idea and it seems to work well. The issue I have is I do a lot of stuff in many different applications (mostly programming IDEs and editors) and I often have to highlight words for various reasons and I quickly noticed that the popup icon can sometimes get in the way of application native icons and other things. 

   Is it possible to have a list of either explicitly allowed or excluded applications in which the extension will only accept, or ignore input from those applications set in a list? 

Thanks,
-MH

**Comment by sunwxg** [comment]
Your idea is to add a applications list, the application in the list will be excluded to show the popup icon. Am I right?

The extension has a shortcut key `Ctrl+Alt+j`  to disable or enable showing popup icon. Is it useful for you?

**Comment by MostHated** [comment]
Yeah, that is fine.
