### ISSUE TITLE
does not save target language, always must login and re-enter

### ISSUE THREAD

**Issue by paulpreibisch** [sunwxg/gnome-shell-extension-dict#33]
This is such a great concept, unfortunately when u click on it and google translate comes up, you are NOT LOGGED IN.  If you manage to log in (which is not easy), it DOES NOT remember your login between sessions, so you always have to set translation language EACH time you use it rendering it useless. I hope this can be fixed

**Comment by sunwxg** [comment]
In this extension settings, you can set the target language.

**Comment by paulpreibisch** [comment]
Thankyou!  I found it - also, I love the ability to see past translations!
